# Next.js Dockerfile.prod


### BUILD
FROM node:22-alpine as builder

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY ./package*.json .

RUN npm ci

COPY . .

RUN npm run build

RUN npm prune --omit=dev


### PRODUCTION
FROM node:22-alpine

RUN apk add --no-cache \
            libc6-compat \
            curl

WORKDIR /app

ENV NODE_ENV=production

RUN addgroup -S egroup -g 1410 && adduser -S euser -u 1410 -G egroup

COPY --from=builder --chown=euser:egroup /app/.next ./.next
COPY --from=builder --chown=euser:egroup /app/public ./public
COPY --from=builder --chown=euser:egroup /app/node_modules ./node_modules
COPY --from=builder --chown=euser:egroup /app/package*.json .
COPY --from=builder --chown=euser:egroup /app/next.config.* ./

USER euser

EXPOSE 3000

CMD ["npm", "start"]