import type { Metadata } from "next";


import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import getMenuItems from "@/functions/getMenuItems";
import { getLanguageLinks } from "@/functions/getLanguageLinks";
import { SwitchLanguageType } from "@/types/types";
import { headers } from "next/headers";
import { getPageData } from "@/functions/getPageData";
import availableLocales from '../../../config/locales.json';

import vars from "@/vars/vars";




// export const metadata: Metadata = {
//   title: "This is Page. The - Page.",
//   description: "Generated by create next app",
// };

const { home } = vars.const.slug;
const { defaultLocale } = vars.const;



export async function generateMetadata({ params }: { params: Promise<{ web?: string[], lang: string }> }): Promise<Metadata> {
  const { web, lang } = await params;
  const pageSlug = web?.join('/') ?? home;

  const fetchedData = await getPageData(pageSlug, lang);

  if (!fetchedData?.pageData) {
    return {
      title: "Page Not Found",
    };
  }

  const { title, excerpt } = fetchedData.pageData.data;

  return {
    title: `${title} | Smaczna Przystań`,
    description: excerpt || "Zapraszamy do Smacznej Przystani",
    alternates: {
      canonical: `/${lang}/${pageSlug === home ? '' : pageSlug}`,
    },
    openGraph: {
      title: title,
      description: excerpt,
      type: 'website',
    },
  };
}

export default async function WebLayout({ children, params }: Readonly<{ children: React.ReactNode, params: Promise<{ web?: string[], lang: string }>}>) {
  
  const { web, lang } = await params;
  
  const pageSlug = web?.join('/') ?? home;
  // const pageSlug = web && web.length > 0 ? web.join('/') : home;
  
  const [urlItems, contentData] = await Promise.all([
    getMenuItems(lang),
    getPageData(pageSlug, lang)
  ]);
  
  const urlItemsInsert = urlItems || [];
  
  const insertAvailableLocales = availableLocales.length > 0 ? availableLocales : [defaultLocale];
  
  const langItemsInsert : SwitchLanguageType = getLanguageLinks(contentData?.pageData,insertAvailableLocales);

  return (
    <>
      <Header menuItems={urlItemsInsert} langItems={langItemsInsert} />
        {children}
      <Footer />
    </>
  )
}