# Strapi Dockerfile.prod


### BUILD
FROM node:22-alpine as builder

RUN apk add --no-cache \
    curl \
    vips-dev \
    build-base \
    gcc \
    autoconf \
    automake \
    libtool \
    nasm \
    python3 \
    make

WORKDIR /app

COPY ./package*.json .

# RUN npm install
# RUN npm ci --omit=dev
RUN npm ci

COPY . .

RUN npm run build

RUN npm prune --omit=dev


### PRODUCTION
FROM node:22-alpine

RUN apk add --no-cache \
    curl \
    libc6-compat \
    vips-dev

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=1337

RUN addgroup -S egroup -g 1410 && adduser -S euser -u 1410 -G egroup

RUN mkdir -p /app/database /app/public/uploads && \
    chown -R euser:egroup /app

COPY --from=builder --chown=euser:egroup /app/package*.json ./
COPY --from=builder --chown=euser:egroup /app/node_modules ./node_modules

COPY --from=builder --chown=euser:egroup /app/dist ./dist
COPY --from=builder --chown=euser:egroup /app/public ./public
COPY --from=builder --chown=euser:egroup /app/tsconfig.json ./tsconfig.json
COPY --from=builder --chown=euser:egroup /app/config ./config

USER euser

EXPOSE 1337

CMD [ "npm", "start" ]